python data_synthesis.py \
    --dataset "tiny-imagenet" \
    --arch-name "resnet18" \
    --ckpt-path "../pretrain/output/imagenet-tiny_resnet18/checkpoint.pth" \
    --exp-name "rn18_bn0.01_[4K]_x_l2_x_tv.crop_5" \
    --ipc 10 \
    --batch-size 100 \
    --lr 0.25 \
    --iteration 1000 \
    --l2-scale 0 --tv-l2 0 --r-bn 0.01 \
    --verifier --store-best-images
